services:
  redis:
    image: redis:latest
    ports: [ "6379:6379" ]
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h 127.0.0.1 -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
