# Generated by Django 5.2.1 on 2025-06-16 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("summarization", "Document Summarization"),
                            ("embedding", "Text Embedding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("operation_description", models.CharField(blank=True, max_length=255)),
                ("tokens", models.PositiveIntegerField(default=0)),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTokenSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_tokens_used", models.PositiveBigIntegerField(default=0)),
                ("chat_tokens", models.PositiveBigIntegerField(default=0)),
                ("summarization_tokens", models.PositiveBigIntegerField(default=0)),
                ("embedding_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_summary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
