# Generated by Django 5.2.1 on 2025-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenusage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="tokenusage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
