# Generated by Django 5.2.1 on 2025-09-26 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_alter_tokenusage_options_alter_tokenusage_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertokensummary",
            name="user",
        ),
        migrations.DeleteModel(
            name="TokenUsage",
        ),
        migrations.DeleteModel(
            name="UserTokenSummary",
        ),
    ]
