# Generated by Django 5.2.1 on 2025-06-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
