# Generated by Django 5.2.1 on 2025-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="namespace",
            field=models.CharField(default="empty", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
