# Generated by Django 5.2.1 on 2025-09-26 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatsession_namespace"),
        ("documents", "0003_alter_document_options_document_is_processed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blob", models.BinaryField()),
                ("size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="document",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="document",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="document",
            name="raw_text",
        ),
        migrations.RemoveField(
            model_name="document",
            name="summary",
        ),
        migrations.AddField(
            model_name="document",
            name="checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="document",
            name="file_ext",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="document",
            name="file_mime",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "session", "created_at"],
                name="documents_d_user_id_383874_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "created_at"], name="documents_d_status_64808e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "session", "file_name"),
                name="uniq_live_doc_per_session_name",
            ),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="fileasset",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset",
                to="documents.document",
            ),
        ),
        migrations.AddIndex(
            model_name="fileasset",
            index=models.Index(
                fields=["checksum"], name="documents_f_checksu_f349c7_idx"
            ),
        ),
    ]
