# Generated by Django 5.2.1 on 2025-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0004_documentcontent_fileasset_remove_document_file_path_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="DocumentContent",
        ),
    ]
