# Generated by Django 5.2.1 on 2025-10-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_summary_delete_documentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='full_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
